### ISSUE TITLE
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__?

### ISSUE THREAD

**Issue by TaigaVanilla** [TaigaVanilla/tier-list-maker#3]
In development environment
After running docker-compose up, web container doesn't start. 

The container log
```
  File "/app/models.py", line 8, in <module>
    db = SQLAlchemy()
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?
```

**Comment by TaigaVanilla** [comment]
There is compatibility issue with SQLAlchemy 2.0.
https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/changes/#version-3-0-2

Need to pin the SQLAlchemy version or use Flask-SQLAlchemy 3.0.2 or later.

**Comment by TaigaVanilla** [comment]
I closed the issue by error. Pressed the wrong button. So reopened.

**Comment by TaigaVanilla** [comment]
There is compatibility issue with SQLAlchemy 2.0.
https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/changes/#version-3-0-2

Need to pin the SQLAlchemy version or use Flask-SQLAlchemy 3.0.2 or later.

**Comment by TaigaVanilla** [comment]
If I upgrade Flask-SQLAlchemy version from 2.5.1 to 3.0.2, another issue will come up. 
In flask shell
```
>>> from models import init
>>> init()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/app/models.py", line 47, in init
    db.create_all()
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 868, in create_all
    self._call_for_binds(bind_key, "create_all")
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 846, in _call_for_binds
    raise sa.exc.UnboundExecutionError(message) from None
sqlalchemy.exc.UnboundExecutionError: 'SQLALCHEMY_DATABASE_URI' config is not set. Bind key 'None' is not in 'SQLALCHEMY_BINDS' config.
```

Because of this, pinning the SQLAlchemy version is safer.
